// Edge Function: create-package
// Creates a new package, sends email notification to receiver, and logs audit entry
// Deno runtime for Supabase Edge Functions

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0'

interface CreatePackageRequest {
  receiver_email: string
  notes?: string
}

interface PackageResponse {
  id: string
  reference: string
  receiver_email: string
  notes: string | null
  status: string
  created_at: string
}

function buildCorsHeaders(origin: string | null) {
  return {
    'Access-Control-Allow-Origin': origin ?? '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Authorization, X-Requested-With, X-Client-Info, apikey, Content-Type',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Max-Age': '86400'
  }
}

serve(async (req) => {
  const origin = req.headers.get('origin')
  const corsHeaders = buildCorsHeaders(origin)

  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Missing authorization header' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

    // User client to verify caller
    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } }
    })

    const { data: { user: callingUser }, error: userError } = await userClient.auth.getUser()
    if (userError || !callingUser) {
      return new Response(
        JSON.stringify({
          error: 'Unauthorized',
          details: userError?.message || 'Could not verify user token'
        }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Check if calling user is warehouse or admin
    const { data: callerProfile, error: profileError } = await userClient
      .from('staff_profiles')
      .select('role, full_name')
      .eq('user_id', callingUser.id)
      .single()

    if (profileError || !callerProfile) {
      return new Response(
        JSON.stringify({
          error: 'Staff profile not found',
          details: profileError?.message
        }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    if (!['warehouse', 'admin'].includes(callerProfile.role)) {
      return new Response(
        JSON.stringify({
          error: 'Only warehouse staff and admins can create packages',
          details: `User role is '${callerProfile.role}'`
        }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Parse request body
    const body: CreatePackageRequest = await req.json()
    const { receiver_email, notes } = body

    if (!receiver_email) {
      return new Response(
        JSON.stringify({ error: 'Missing required field: receiver_email' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(receiver_email)) {
      return new Response(
        JSON.stringify({ error: 'Invalid email format' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Admin client for operations
    const adminClient = createClient(supabaseUrl, supabaseServiceKey, {
      auth: { autoRefreshToken: false, persistSession: false }
    })

    // Create package (reference is auto-generated by trigger)
    const { data: newPackage, error: packageError } = await adminClient
      .from('packages')
      .insert({
        receiver_email: receiver_email.toLowerCase().trim(),
        notes: notes?.trim() || null,
        created_by: callingUser.id,
        status: 'pending'
      })
      .select()
      .single()

    if (packageError) {
      console.error('Package creation error:', packageError)
      return new Response(
        JSON.stringify({
          error: 'Failed to create package',
          details: packageError.message
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Send email notification to receiver
    let emailSent = false
    let emailError: string | null = null

    try {
      // Use Resend API if configured, otherwise log for manual follow-up
      const resendApiKey = Deno.env.get('RESEND_API_KEY')

      if (resendApiKey) {
        const emailResponse = await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${resendApiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            from: Deno.env.get('EMAIL_FROM') || 'POD System <noreply@example.com>',
            to: [receiver_email],
            subject: `Package Ready for Collection - ${newPackage.reference}`,
            html: `
              <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <h2 style="color: #1e3a5f;">Package Notification</h2>
                <p>Hello,</p>
                <p>A package has been registered for you and is ready for collection.</p>
                <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                  <p style="margin: 0 0 10px 0;"><strong>Reference Number:</strong></p>
                  <p style="font-size: 24px; font-weight: bold; color: #1e3a5f; margin: 0;">${newPackage.reference}</p>
                  ${notes ? `<p style="margin: 15px 0 0 0;"><strong>Notes:</strong> ${notes}</p>` : ''}
                </div>
                <p>Please present this reference number when collecting your package.</p>
                <p style="color: #6b7280; font-size: 14px; margin-top: 30px;">
                  This is an automated message from the POD System.
                </p>
              </div>
            `
          })
        })

        if (emailResponse.ok) {
          emailSent = true
          // Update package status to notified
          await adminClient
            .from('packages')
            .update({ status: 'notified' })
            .eq('id', newPackage.id)

          newPackage.status = 'notified'
        } else {
          const errorBody = await emailResponse.text()
          emailError = `Email API error: ${errorBody}`
          console.error('Email send failed:', emailError)
        }
      } else {
        emailError = 'Email service not configured (RESEND_API_KEY not set)'
        console.log('Email notification skipped:', emailError)
      }
    } catch (e) {
      emailError = `Email exception: ${e.message}`
      console.error('Email send exception:', e)
    }

    // Create audit log entry
    const { error: auditError } = await adminClient
      .from('audit_logs')
      .insert({
        action: 'PACKAGE_CREATED',
        entity_type: 'package',
        entity_id: newPackage.id,
        performed_by: callingUser.id,
        metadata: {
          reference: newPackage.reference,
          receiver_email: newPackage.receiver_email,
          notes: newPackage.notes,
          email_sent: emailSent,
          email_error: emailError,
          created_by_name: callerProfile.full_name
        }
      })

    if (auditError) {
      console.error('Audit log error:', auditError)
      // Don't fail the request for audit log errors
    }

    // Return created package
    const response: PackageResponse = {
      id: newPackage.id,
      reference: newPackage.reference,
      receiver_email: newPackage.receiver_email,
      notes: newPackage.notes,
      status: newPackage.status,
      created_at: newPackage.created_at
    }

    return new Response(
      JSON.stringify({
        package: response,
        email_sent: emailSent,
        email_error: emailError
      }),
      { status: 201, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Unexpected error:', error)
    return new Response(
      JSON.stringify({
        error: 'Internal server error',
        details: error.message
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
