/**
 * Package status definitions for the POD system.
 * - pending: Package registered, awaiting notification
 * - notified: Receiver has been notified via email
 * - collected: Package has been collected by receiver
 * - returned: Package was returned (unclaimed)
 */
export type PackageStatus = 'pending' | 'notified' | 'collected' | 'returned';

/**
 * Package interface matching the database schema.
 */
export interface Package {
  id: string;
  reference: string;
  receiver_email: string;
  notes: string | null;
  status: PackageStatus;
  created_by: string;
  created_at: string;
  updated_at: string;
  collected_at: string | null;
  collected_by: string | null;
  // POD signature fields
  signature_url: string | null;
  signature_path: string | null;
  signed_at: string | null;
  // POD reference
  pod_id: string | null;
}

/**
 * DTO for creating a new package.
 * Reference is auto-generated by the database.
 */
export interface CreatePackageDto {
  receiver_email: string;
  notes?: string;
}

/**
 * DTO for updating a package status.
 */
export interface UpdatePackageDto {
  status?: PackageStatus;
  notes?: string;
}

/**
 * Package with creator details for display.
 */
export interface PackageWithCreator extends Package {
  creator_name?: string;
  creator_email?: string;
}

/**
 * Status configuration for display
 */
export const PACKAGE_STATUS_CONFIG: Record<PackageStatus, { label: string; color: string; icon: string }> = {
  pending: {
    label: 'Pending',
    color: '#f59e0b',
    icon: 'clock'
  },
  notified: {
    label: 'Notified',
    color: '#3b82f6',
    icon: 'mail'
  },
  collected: {
    label: 'Collected',
    color: '#10b981',
    icon: 'check'
  },
  returned: {
    label: 'Returned',
    color: '#ef4444',
    icon: 'undo'
  }
};
