/**
 * Package status definitions for the POD system.
 * - pending: Package registered, being prepared
 * - notified: Initial notification sent (package being prepared)
 * - in_transit: Driver picked up package, on the way to collection point
 * - ready_for_collection: Package arrived at collection point, ready for pickup
 * - collected: Package has been collected by receiver
 * - returned: Package was returned (unclaimed)
 */
export type PackageStatus = 'pending' | 'notified' | 'in_transit' | 'ready_for_collection' | 'collected' | 'returned';

/**
 * Package item representing an individual item in a package.
 */
export interface PackageItem {
  id?: string;
  package_id?: string;
  quantity: number;
  description: string;
  created_at?: string;
}

/**
 * Package interface matching the database schema.
 */
export interface Package {
  id: string;
  reference: string;
  receiver_email: string;
  notes: string | null;
  status: PackageStatus;
  created_by: string;
  created_at: string;
  updated_at: string;
  collected_at: string | null;
  collected_by: string | null;
  // Driver pickup tracking
  picked_up_by: string | null;
  picked_up_at: string | null;
  // Collection point receiving tracking
  received_by: string | null;
  received_at: string | null;
  // POD signature fields
  signature_url: string | null;
  signature_path: string | null;
  signed_at: string | null;
  // POD reference
  pod_id: string | null;
  // Delivery location
  delivery_location_id: string | null;
  delivery_location?: {
    id: string;
    name: string;
    address: string;
    google_maps_link: string | null;
  };
  // Purchase order number
  po_number: string | null;
  // Package items
  items?: PackageItem[];
}

/**
 * DTO for creating a new package.
 * Reference is auto-generated by the database.
 */
export interface CreatePackageDto {
  receiver_email: string;
  notes?: string;
  items?: { quantity: number; description: string }[];
  delivery_location_id?: string;
  po_number?: string;
}

/**
 * DTO for updating a package status.
 */
export interface UpdatePackageDto {
  status?: PackageStatus;
  notes?: string;
}

/**
 * Package with creator details for display.
 */
export interface PackageWithCreator extends Package {
  creator_name?: string;
  creator_email?: string;
}

/**
 * Status configuration for display
 */
export const PACKAGE_STATUS_CONFIG: Record<PackageStatus, { label: string; color: string; icon: string }> = {
  pending: {
    label: 'Pending',
    color: '#f59e0b',
    icon: 'clock'
  },
  notified: {
    label: 'Being Prepared',
    color: '#8b5cf6',
    icon: 'package'
  },
  in_transit: {
    label: 'In Transit',
    color: '#3b82f6',
    icon: 'truck'
  },
  ready_for_collection: {
    label: 'Ready for Collection',
    color: '#10b981',
    icon: 'check-circle'
  },
  collected: {
    label: 'Collected',
    color: '#059669',
    icon: 'check'
  },
  returned: {
    label: 'Returned',
    color: '#ef4444',
    icon: 'undo'
  }
};
